version: '3'

services:
  api:
    image: ugc-api:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - 'database'
    container_name: api
    networks:
      - "ugc-rep-default"
    volumes:
      - "/home/atopi/IdeaProjects/UGC-repository/db/masterkey.txt:/data/masterkey.txt:ro"

  database:
    image: mariadb:10.4.12-bionic
    ports:
      - "3306:3306"
    container_name: database
    restart: always
    networks:
      - "ugc-rep-default"
    volumes:
      - "db-data:/var/lib/mysql:rw"
      - "/home/atopi/IdeaProjects/UGC-repository/db/logs:/var/log/mysql:rw"
      - "/home/atopi/IdeaProjects/UGC-repository/db/mariadb.cnf:/etc/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: ${dbRootPW}

networks:
  ugc-rep-default:

volumes:
  db-data: