
POST http://localhost:8080/rest/applications
Content-Type: application/x-www-form-urlencoded
Accept: application/x-www-form-urlencoded

application_id=12&application_name=xform2

###

POST http://localhost:8080/rest/applications
Content-Type: application/json

{
  "application_id": 1,
  "application_name": "json2"
}

###

POST http://localhost:8080/rest/applications
Content-Type: application/xml
Accept: application/xml

<?xml version="1.0" encoding="UTF-8"?>
<application>
    <application_name>xml5</application_name>
    <application_id>1</application_id>
</application>

###

POST http://localhost:8080/rest/applications
Content-Type: text/plain

application_id,application_name
1,test18

###

PATCH http://localhost:8080/rest/applications
Content-Type: application/json

{
  "application_id": 1,
  "application_name": "cuby"
}

###

PUT http://localhost:8080/rest/applications/0
Content-Type: application/json

{
  "application_id": 0,
  "application_name": "cuby"
}

###

DELETE http://localhost:8080/rest/applications/5

###

GET http://localhost:8080/rest/applications
Accept: text/csv

###

HEAD http://localhost:8080/rest/applications?format=json
Accept: application/json

###

OPTIONS http://localhost:8080/rest/applications
Accept: application/json

###

TRACE http://localhost:8080/rest/applications
Accept: application/json

###